# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Revivendo o Theatro Melpômene
email: colette@colettedantas.com
description: > # this means to ignore newlines until "baseurl:"
  Revivendo o Theatro Melpômene
baseurl:  # the subpath of your site, e.g. /blog
url: "http://theatromelpomene.com" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
twitter_username: colettedantas
github_username:  
facebook_username: 
#instagram_username: beyonce
#stackoverflow_url: https://
#googleplus_username: BobMarley
#skype_username: echo123
#linkedin_url: https://

# Address information
address_street: Praça Costa Pereira
address_city: Vitória
address_state: ES
address_zip: 

# Build settings
markdown: kramdown
